package com.example.finanzas_independientes_app.core.network

/**
 * Canonical catalog of backend `code` values. The client branches on these,
 * never on human-facing messages. Unknown server codes map to [UNKNOWN] so a
 * new backend code never crashes the client.
 */
enum class ApiCode(val raw: String) {
    // --- Success: auth ---
    LOGIN_SUCCESS("LOGIN_SUCCESS"),
    USER_REGISTERED("USER_REGISTERED"),
    TOKEN_REFRESHED("TOKEN_REFRESHED"),
    OTP_SENT("OTP_SENT"),
    OTP_VERIFIED("OTP_VERIFIED"),
    PASSWORD_RESET_SUCCESS("PASSWORD_RESET_SUCCESS"),
    BUSINESS_UPDATED("BUSINESS_UPDATED"),
    PROFILE_OK("PROFILE_OK"),
    PROFILE_UPDATED("PROFILE_UPDATED"),
    LOGGED_OUT("LOGGED_OUT"),

    // --- Success: finanzas ---
    TRANSACTION_CREATED("TRANSACTION_CREATED"),
    TRANSACTIONS_OK("TRANSACTIONS_OK"),
    TRANSACTION_UPDATED("TRANSACTION_UPDATED"),
    TRANSACTION_DELETED("TRANSACTION_DELETED"),
    TODAY_INCOME_OK("TODAY_INCOME_OK"),
    DAILY_QUOTA_OK("DAILY_QUOTA_OK"),
    WEEKLY_SUMMARY_OK("WEEKLY_SUMMARY_OK"),
    GOALS_PROGRESS_OK("GOALS_PROGRESS_OK"),
    GOAL_SET("GOAL_SET"),
    GOAL_OK("GOAL_OK"),
    CATEGORIES_OK("CATEGORIES_OK"),
    CATEGORY_CREATED("CATEGORY_CREATED"),
    CATEGORY_SUMMARY_OK("CATEGORY_SUMMARY_OK"),
    CATEGORY_UPDATED("CATEGORY_UPDATED"),
    CATEGORY_DELETED("CATEGORY_DELETED"),
    MONTHLY_TREND_OK("MONTHLY_TREND_OK"),
    FINANCIAL_HEALTH_OK("FINANCIAL_HEALTH_OK"),
    DAILY_SUMMARY_OK("DAILY_SUMMARY_OK"),
    TREND_OK("TREND_OK"),
    WEEKDAY_INCOME_OK("WEEKDAY_INCOME_OK"),
    BUDGET_SET("BUDGET_SET"),
    BUDGETS_OK("BUDGETS_OK"),
    BUDGET_DELETED("BUDGET_DELETED"),
    CATEGORY_COMPARISON_OK("CATEGORY_COMPARISON_OK"),
    MONTHLY_PROJECTION_OK("MONTHLY_PROJECTION_OK"),

    // --- Financial health signals (nested in data) ---
    GASTO_DIARIO_ALTO("GASTO_DIARIO_ALTO"),
    META_CERCA("META_CERCA"),
    META_EN_RIESGO("META_EN_RIESGO"),
    EGRESOS_SUPERAN_INGRESOS("EGRESOS_SUPERAN_INGRESOS"),
    TASA_AHORRO_BAJA("TASA_AHORRO_BAJA"),
    TASA_AHORRO_SANA("TASA_AHORRO_SANA"),
    PRESUPUESTO_EXCEDIDO("PRESUPUESTO_EXCEDIDO"),
    PROYECCION_BAJO_META("PROYECCION_BAJO_META"),

    // --- Errors ---
    VALIDATION_ERROR("VALIDATION_ERROR"),
    MALFORMED_JSON("MALFORMED_JSON"),
    UNAUTHORIZED("UNAUTHORIZED"),
    REFRESH_TOKEN_INVALIDO("REFRESH_TOKEN_INVALIDO"),
    FORBIDDEN("FORBIDDEN"),
    ACCESO_DENEGADO("ACCESO_DENEGADO"),
    USUARIO_NO_ENCONTRADO("USUARIO_NO_ENCONTRADO"),
    TRANSACCION_NO_ENCONTRADA("TRANSACCION_NO_ENCONTRADA"),
    META_NO_ENCONTRADA("META_NO_ENCONTRADA"),
    CATEGORIA_NO_ENCONTRADA("CATEGORIA_NO_ENCONTRADA"),
    EMAIL_DUPLICADO("EMAIL_DUPLICADO"),
    OTP_INVALIDO("OTP_INVALIDO"),
    OTP_EXPIRADO("OTP_EXPIRADO"),
    OTP_BLOQUEADO("OTP_BLOQUEADO"),
    PARAMETRO_INVALIDO("PARAMETRO_INVALIDO"),
    RANGO_FECHAS_INVALIDO("RANGO_FECHAS_INVALIDO"),
    INTERNAL_SERVER_ERROR("INTERNAL_SERVER_ERROR"),

    /** Fallback for any code not yet modeled here. */
    UNKNOWN("UNKNOWN");

    companion object {
        private val byRaw = entries.associateBy { it.raw }

        fun from(raw: String?): ApiCode = byRaw[raw] ?: UNKNOWN
    }
}
